version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/extraction-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/verify_health.sh
      timeout: 60
      runas: ubuntu
